//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asf.RoadWorks.BusinessLogic.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asf.RoadWorks.BusinessLogic.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;account {0} è già presente nel sistema..
        /// </summary>
        public static string Account_AlreadyExists {
            get {
                return ResourceManager.GetString("Account_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;account non è stato trovato..
        /// </summary>
        public static string Account_NotFound {
            get {
                return ResourceManager.GetString("Account_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato trovato un ruolo da assegnare all&apos;account..
        /// </summary>
        public static string Account_Role_NotFound {
            get {
                return ResourceManager.GetString("Account_Role_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato trovato audit per il lavoro con identificativo: {0}..
        /// </summary>
        public static string Audit_NotFound {
            get {
                return ResourceManager.GetString("Audit_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;impresa \&quot;{0}\&quot; è già presente nella base dati..
        /// </summary>
        public static string Company_AlreadyExists {
            get {
                return ResourceManager.GetString("Company_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stata trovata nessuna ditta con codice identificativo \&quot;{0}\&quot;..
        /// </summary>
        public static string Company_NotFound {
            get {
                return ResourceManager.GetString("Company_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile cancellare la ditta con identificativo \&quot;{0}\&quot; perché ci sono ancora dei responsabili collegati..
        /// </summary>
        public static string Company_UsersExist_NotDeleted {
            get {
                return ResourceManager.GetString("Company_UsersExist_NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile cancellare la ditta con identificativo \&quot;{0}\&quot; perché è collegata a dei lavori..
        /// </summary>
        public static string Company_WorksExist_NotDeleted {
            get {
                return ResourceManager.GetString("Company_WorksExist_NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditta.
        /// </summary>
        public static string CompanyId {
            get {
                return ResourceManager.GetString("CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditta / UO è obbligatoria.
        /// </summary>
        public static string CompanyIsMandatory {
            get {
                return ResourceManager.GetString("CompanyIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È già stata inserita una configurazione per l&apos;anno \&quot;{0}\&quot;..
        /// </summary>
        public static string Configuration_AlreadyExists {
            get {
                return ResourceManager.GetString("Configuration_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stata trovata nessuna configurazione..
        /// </summary>
        public static string Configuration_NotFound {
            get {
                return ResourceManager.GetString("Configuration_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenuto.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruolo non valido.
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unità Operativa.
        /// </summary>
        public static string IsOperationalUnit {
            get {
                return ResourceManager.GetString("IsOperationalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log non trovato..
        /// </summary>
        public static string Log_NotFound {
            get {
                return ResourceManager.GetString("Log_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome del file di log.
        /// </summary>
        public static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorso del file di log.
        /// </summary>
        public static string LogFilePath {
            get {
                return ResourceManager.GetString("LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data importazione.
        /// </summary>
        public static string MigrationDate {
            get {
                return ResourceManager.GetString("MigrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sede stradale \&quot;{0}\&quot; è già presente nella base dati..
        /// </summary>
        public static string Roadway_AlreadyExists {
            get {
                return ResourceManager.GetString("Roadway_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stata trovata nessuna sede stradale..
        /// </summary>
        public static string Roadway_NotFound {
            get {
                return ResourceManager.GetString("Roadway_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile cancellare la sede stradale con identificativo &quot;{0}&quot; perché è collegata a dei lavori..
        /// </summary>
        public static string Roadway_WorksExist_NotDeleted {
            get {
                return ResourceManager.GetString("Roadway_WorksExist_NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;indirizzo: &quot;{0}&quot; è inesistente..
        /// </summary>
        public static string RoadWork_Address_NotExists {
            get {
                return ResourceManager.GetString("RoadWork_Address_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il civico: &quot;{0}&quot; è inesistente..
        /// </summary>
        public static string RoadWork_AddressNumber_NotExists {
            get {
                return ResourceManager.GetString("RoadWork_AddressNumber_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;estensione {0} non è valida. Le estensioni valide sono csv, xls e xlsx..
        /// </summary>
        public static string RoadWork_Attachment_InvalidExtension {
            get {
                return ResourceManager.GetString("RoadWork_Attachment_InvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allegato non trovato..
        /// </summary>
        public static string RoadWork_Attachment_NotFound {
            get {
                return ResourceManager.GetString("RoadWork_Attachment_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per un lavoro {0} è obbligatorio specificare una data (stimata e/o effettiva)..
        /// </summary>
        public static string RoadWork_Date_IsMandatory {
            get {
                return ResourceManager.GetString("RoadWork_Date_IsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato specificato nessuno stato valido per il lavoro stradale non programmato. Lo stato per i lavori non programmati è obbligatorio..
        /// </summary>
        public static string RoadWork_InvalidScheduler {
            get {
                return ResourceManager.GetString("RoadWork_InvalidScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato trovato nessun lavoro..
        /// </summary>
        public static string RoadWork_NotFound {
            get {
                return ResourceManager.GetString("RoadWork_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaduti i termini di validità della presentazione dei lavori..
        /// </summary>
        public static string RoadWork_Terms_Expired {
            get {
                return ResourceManager.GetString("RoadWork_Terms_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il periodo di presentazione dei lavori per l&apos;anno &quot;{0}&quot; è scaduto..
        /// </summary>
        public static string RoadWork_Year_Expired {
            get {
                return ResourceManager.GetString("RoadWork_Year_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ricerca per range annuale non può essere superiore ai 5 anni..
        /// </summary>
        public static string RoadWork_Year_InvalidRange {
            get {
                return ResourceManager.GetString("RoadWork_Year_InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fine presentazione lavori.
        /// </summary>
        public static string SubmissionEndDate {
            get {
                return ResourceManager.GetString("SubmissionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inizio presentazione lavori.
        /// </summary>
        public static string SubmissionStartDate {
            get {
                return ResourceManager.GetString("SubmissionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dati responsabile ditta..
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsabile della ditta non trovato..
        /// </summary>
        public static string User_NotFound {
            get {
                return ResourceManager.GetString("User_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente già esistente.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il nome della vista &quot;{0}&quot; non è valido..
        /// </summary>
        public static string ViewName_IsNotValid {
            get {
                return ResourceManager.GetString("ViewName_IsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anno.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
