CREATE TABLE [RoadWorks].[Works]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL,
	[AuthorityId] BIGINT NOT NULL,
	[CompanyId] BIGINT NOT NULL,
	[Year] SMALLINT NOT NULL,
	[IsOverlap] BIT NOT NULL,
	[Priority] TINYINT NULL,
	[Status] TINYINT NULL,
	[Address] NVARCHAR(512) NOT NULL,
	[AddressPointFrom] [sys].[geography] NULL,
	[AddressPointTo] [sys].[geography] NULL,
	[PinPoint] [sys].[geography] NULL,
	[Category] TINYINT NOT NULL,
	[NotScheduledStatus] TINYINT NULL,
	[NotPlannedStatus] TINYINT NULL,
	[Description] NVARCHAR(2048) NOT NULL,
	[DescriptionForCitizens] NVARCHAR(MAX) NULL,
	[TrafficChangesMeasure] NVARCHAR(2048) NULL,
	[Notes] NVARCHAR(MAX) NULL,
	[EffectiveStartDate] DATETIME NULL,
	[EffectiveEndDate] DATETIME NULL,
	[EstimatedStartDate] DATETIME NULL,
	[EstimatedEndDate] DATETIME NULL,
	[AddressNumberFrom] NVARCHAR(20) NULL, 
	[AddressNumberTo] NVARCHAR(20) NULL,
	[GeoFeatureContainer] NTEXT NULL,
	[VisualizationNotes] NVARCHAR(2048) NULL,
	[Link] NVARCHAR(256) NULL,
	[MunicipalityReferentName] NVARCHAR(100) NULL,
	[MunicipalityReferentPhoneNumber] NVARCHAR(50) NULL,
	[CompanyReferentName] NVARCHAR(100) NULL,
	[CompanyReferentPhoneNumber] NVARCHAR(50) NULL,
	[PublishStatus] TINYINT NULL, 
	CONSTRAINT [PK_Works] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_Works_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [RoadWorks].[Companies] ([Id])
)